import { ConnectButton } from "@rainbow-me/rainbowkit";
import Link from "next/link";
import React from "react";
import Head from "next/head";
import { Button } from "./Buttons";
import { ConnectionButton } from "./ConnectionButton";

const Navbar = () => {
  return (
    <>
      <Head>
        <title>CeloPool</title>
        <meta name="description" content="Generated by create next app" />
        <meta content="CeloPool" property="og:title" />
        <meta content="CeloPool" property="twitter:title" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="icon.jpg" rel="shortcut icon" type="image/x-icon" />
        <link href="icon.jpg" rel="apple-touch-icon" />
        <link href="icon.jpg" rel="apple-touch-icon" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="flex justify-between items-center py-4 px-4 md:px-8 nav__bar">
        <div className="text-white flex items-center font-medium text-xl">
          <Link href={"/"}>
            <div className="product__logo flex items-center">
              <p className="font-mono font-semibold">CeloPool</p>
            </div>
          </Link>
          <Link href="/market" className="">
            <a className="navbar__market">Markets</a>
          </Link>
          <Link href="/partners">
            <a className="ml-4 navbar___partner">Partners</a>
          </Link>
          <Link target="_blank" href="https://celopool-dex-frontend-ajbwvr6ni-celopool.vercel.app/">
            <a className="ml-4 navbar___partner">DEX</a>
          </Link>
        </div>

        <div className="flex items-center">
          <ConnectionButton></ConnectionButton>
        </div>
      </div>
    </>
  );
};

export default Navbar;
